/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Random;


public class App {
    public static void main(String[] args) throws FileNotFoundException {
        Gson gson = new Gson();
        Random rand = new Random();

        File quoteFile = new File("app/src/main/resources/recentquotes.json");

        FileReader quoteReader = new FileReader(quoteFile);


        TypeToken<Collection<Quote>> collectionType = new TypeToken<Collection<Quote>>(){};


        Collection<Quote> collection = gson.fromJson(quoteReader, collectionType);

//        ArrayList<Quote> list = Arrays.asList(collection.addAll());

        ArrayList<Quote> list = new ArrayList<>();

        for (Quote element : collection){
            list.add(element);
        }
        int randomIndex = rand.nextInt(list.size()-1);

        System.out.println("Author: " + list.get(randomIndex).author +" \nQuote: " + list.get(randomIndex).text);
    }
}
